// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: api/proto/event.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventIngestion_SendEvent_FullMethodName  = "/streamflow.EventIngestion/SendEvent"
	EventIngestion_SendBatch_FullMethodName  = "/streamflow.EventIngestion/SendBatch"
	EventIngestion_SendStream_FullMethodName = "/streamflow.EventIngestion/SendStream"
)

// EventIngestionClient is the client API for EventIngestion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventIngestionClient interface {
	// Отправка одиночного события
	SendEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventResponse, error)
	// Отправка батча событий
	SendBatch(ctx context.Context, in *EventBatch, opts ...grpc.CallOption) (*BatchResponse, error)
	// Stream для непрерывной отправки событий
	SendStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, EventResponse], error)
}

type eventIngestionClient struct {
	cc grpc.ClientConnInterface
}

func NewEventIngestionClient(cc grpc.ClientConnInterface) EventIngestionClient {
	return &eventIngestionClient{cc}
}

func (c *eventIngestionClient) SendEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, EventIngestion_SendEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventIngestionClient) SendBatch(ctx context.Context, in *EventBatch, opts ...grpc.CallOption) (*BatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, EventIngestion_SendBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventIngestionClient) SendStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Event, EventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventIngestion_ServiceDesc.Streams[0], EventIngestion_SendStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, EventResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngestion_SendStreamClient = grpc.BidiStreamingClient[Event, EventResponse]

// EventIngestionServer is the server API for EventIngestion service.
// All implementations must embed UnimplementedEventIngestionServer
// for forward compatibility.
type EventIngestionServer interface {
	// Отправка одиночного события
	SendEvent(context.Context, *Event) (*EventResponse, error)
	// Отправка батча событий
	SendBatch(context.Context, *EventBatch) (*BatchResponse, error)
	// Stream для непрерывной отправки событий
	SendStream(grpc.BidiStreamingServer[Event, EventResponse]) error
	mustEmbedUnimplementedEventIngestionServer()
}

// UnimplementedEventIngestionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventIngestionServer struct{}

func (UnimplementedEventIngestionServer) SendEvent(context.Context, *Event) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendEvent not implemented")
}
func (UnimplementedEventIngestionServer) SendBatch(context.Context, *EventBatch) (*BatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBatch not implemented")
}
func (UnimplementedEventIngestionServer) SendStream(grpc.BidiStreamingServer[Event, EventResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SendStream not implemented")
}
func (UnimplementedEventIngestionServer) mustEmbedUnimplementedEventIngestionServer() {}
func (UnimplementedEventIngestionServer) testEmbeddedByValue()                        {}

// UnsafeEventIngestionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventIngestionServer will
// result in compilation errors.
type UnsafeEventIngestionServer interface {
	mustEmbedUnimplementedEventIngestionServer()
}

func RegisterEventIngestionServer(s grpc.ServiceRegistrar, srv EventIngestionServer) {
	// If the following call pancis, it indicates UnimplementedEventIngestionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventIngestion_ServiceDesc, srv)
}

func _EventIngestion_SendEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestionServer).SendEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngestion_SendEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestionServer).SendEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventIngestion_SendBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventIngestionServer).SendBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventIngestion_SendBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventIngestionServer).SendBatch(ctx, req.(*EventBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventIngestion_SendStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventIngestionServer).SendStream(&grpc.GenericServerStream[Event, EventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventIngestion_SendStreamServer = grpc.BidiStreamingServer[Event, EventResponse]

// EventIngestion_ServiceDesc is the grpc.ServiceDesc for EventIngestion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventIngestion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streamflow.EventIngestion",
	HandlerType: (*EventIngestionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEvent",
			Handler:    _EventIngestion_SendEvent_Handler,
		},
		{
			MethodName: "SendBatch",
			Handler:    _EventIngestion_SendBatch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendStream",
			Handler:       _EventIngestion_SendStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/event.proto",
}
